apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
    external-dns.alpha.kubernetes.io/hostname: grafana.lab.naimaosmann.com
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - grafana.lab.naimaosmann.com
    secretName: grafana-tls
  rules:
  - host: grafana.lab.naimaosmann.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80