name: Update Deployment Image Tag 

on:
  workflow_run:
    workflows: ["Publish Container Image to ECR"]
    types: [completed]
    branches: [main]

permissions:
  contents: write

jobs:
  update-image-tag:
    name: Update image tag 
    runs-on: ubuntu-latest 

    # skip if build workflow fails
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with: 
          ref: main

      - name: install yq
        uses: mikefarah/yq@v4

      - name: update image tag in deployment.yaml
        run: |
          SHA=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-8)
          IMAGE="${{ secrets.IMAGE }}:$SHA"
          yq e -i '(.spec.template.spec.containers[] | select(.name == "eks-app-img") | .image) = "'"$IMAGE"'"' \
            infra/kubernetes/app/deployment.yaml
      - name: Commit and push
        run: |
          SHA=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-8)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet && exit 0
          git add infra/kubernetes/app/deployment.yaml
          git commit -m "chore: deploy image tag $SHA [skip ci]"
          git push
